### ISSUE TITLE
Grid builder generating unwanted css classes in frontend

### ISSUE THREAD

**Issue by SeptimusVII** [Web-Ex-Machina/contao-smartgear#150]
see following screenshot. 
Pink highlight means  "not a problem now, but could certainly be"
Orange highlight means "not really a problem, but useless and kinda ugly

![image](https://user-images.githubusercontent.com/28646786/175315389-04424094-45f0-4a6e-829c-6740e26cbcd9.png)

**Comment by ChipsVII** [comment]
The `contao-grid` have been updated, tell me if it needs further fixes.
