### ISSUE TITLE
Grid builder - issue batch 1 (01/07/22)

### ISSUE THREAD

**Issue by SeptimusVII** [Web-Ex-Machina/contao-smartgear#164]

**Comment by SeptimusVII** [comment]
field “Preset” should not exist
   
![Untitled](https://user-images.githubusercontent.com/28646786/176916527-a69e57a3-ee98-464b-a1e9-f8e9a8a73bc5.png)

**Comment by SeptimusVII** [comment]
field “Resolution” should display its values in desc order, from the highest value (Desktop) to the lowest  (XXS)
![Untitled](https://user-images.githubusercontent.com/28646786/176916604-89e9679c-85f2-4a8f-9b9a-86359afa5ee8.png)

**Comment by SeptimusVII** [comment]
this elements and features are not parts of the specifications
![Untitled](https://user-images.githubusercontent.com/28646786/176916936-77de0814-7e3e-4dd6-ba21-1f1ade2d4085.png)

**Comment by SeptimusVII** [comment]
moving an item over another one, in first or last place in the grid, seems to work as intended. thus, the grey squares in first and last position don't look like they are necessary anymore ?
if they aren't, we should remove them, as they might be source of confusion for users 
![Untitled](https://user-images.githubusercontent.com/28646786/176917037-e9154f15-4219-45da-ae2e-ba1380d236d6.png)

**Comment by SeptimusVII** [comment]
problem of inheritance. according to sepcifications: “lower resolutions inherit the configuration of the resolution directly above them”. this, work as intended in frontend, but do not reflect it in the preview

![Untitled](https://user-images.githubusercontent.com/28646786/176917249-19a0aa0e-db52-48bd-8505-6055d2beac9f.png)
state of the grid on Desktop - OK

![Untitled](https://user-images.githubusercontent.com/28646786/176917135-fb69a9dc-5451-48a2-bb1f-701ed4d175bb.png)
State of the grid on XL - not OK. the first item should span on 2 cols, because it was defined as such on Desktop and will stay like this on all lower resolution, until a new spanning is defined for this item.

solution —> unless the colspan field of an item as a value, apply the higher resolution configuration

**Comment by SeptimusVII** [comment]
on lower resolution, if no number of columns is defined, the colspan field of items are empty. This should not occur, as number of columns has been defined on higher resolution
![Untitled](https://user-images.githubusercontent.com/28646786/176917380-028480f4-eb39-48d3-8155-073a310a5709.png)

**Comment by ChipsVII** [comment]
Done, available for tests on the sandbox
