### ISSUE TITLE
Header : tests 13/09

### ISSUE THREAD

**Issue by ChipsVII** [Web-Ex-Machina/contao-smartgear#197]
## Logo
- [x] On the homepage, should we keep the link on the logo?
In the v1, we put the h1 on the logo, so we are sure to have a lvl 1 title coherent. But on some websites, the homepage can have a more pertinent h1 in the page, so maybe we should have a setting for that? Like a dropdown labeled "Logo wrapper on the homepage" with the options "div", "a" or "h1" ?

## Search

- [x] Once a search is done, the keywords appear in the URL but not in the search field (desired behavior ?)
- [x] Once a search is done, the search field should be deployed automatically

## Width / responsive
- [x] If header width set to "page body" and a top bar is configured, the top bar content isn't limited to page body width (desired behavior ?)

<details>
  <summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/93145825/189826401-7624eb28-bd64-4231-9ed3-ad6bbb1aa329.png)
</details>

- [x] The translation, when going to a subpage, feels off. It comes from the bottom of the screen when the chevron points to the right.
- [x] Do not know if it is the cache but on mobile, the search field is going mad. The Android keyboard tries to open and closes up directly.
- [x] Should the search field takes all the screen width since we do not have much place?

## Navigation
- [x]  **Desktop** : There is no indication/sign that a 2nd level link leads to a 3rd one unless we hover it (desired behavior ?)
<details>
    <summary>Screenshots</summary>

**When hovering "Agenda"**

![image](https://user-images.githubusercontent.com/93145825/189829762-a765eef5-6624-43a8-bca4-095a85f618d8.png)

**When hovering, "Subpage test 3 (copie)"**

![image](https://user-images.githubusercontent.com/93145825/189829825-13fb670d-a4aa-45e5-b127-1d0142723350.png)

</details>

## Config
- [x] Should we forbid the possibility to add a multilingual setting to the header if the module "change-language" does not exist?
- [x] Should we restrict the language selector dropdown to the change-language module?
- [x] The search config should have the GET argument name, we might want to use another term than "keywords"

**Comment by SeptimusVII** [comment]
#171

**Comment by SeptimusVII** [comment]
> ## Logo
> * [ ]  On the homepage, should we keep the link on the logo?
>   In the v1, we put the h1 on the logo, so we are sure to have a lvl 1 title coherent. But on some websites, the homepage can have a more pertinent h1 in the page, so maybe we should have a setting for that? Like a dropdown labeled "Logo wrapper on the homepage" with the options "div", "a" or "h1" ?

Septimus: could be... may be a bit of an overkill for now. @LupusVII your thoughts ?

> ## Search
> * [ ]  Once a search is done, the keywords appear in the URL but not in the search field (desired behavior ?)
> * [ ]  Once a search is done, the search field should be deployed automatically

Septimus: yes and yes
 
> ## Width / responsive
> * [ ]  If header width set to "page body" and a top bar is configured, the top bar content isn't limited to page body width (desired behavior ?)

Septimus: desired behavior, yes. the topbar is a free html content field, which mean the user can do it by himself if wanted

> * [ ]  The translation, when going to a subpage, feels off. It comes from the bottom of the screen when the chevron points to the right.

Septimus: aware of this, but will take me a good chunk of time to improve that. Currently, I did mostly nothing on this animation, it is a product of the panels switch mechanic, and dealing with the animation may force me to change the way things works. For now it's good enough for me, @LupusVII your thoughts on it ?

> * [ ]  Do not know if it is the cache but on mobile, the search field is going mad. The Android keyboard tries to open and closes up directly.

Septimus: buggy, yes, I'll fix that

> * [ ]  Should the search field takes all the screen width since we do not have much place?

Septimus: currently min-width of the field is 150px. I can up it to 200px, seems like enough space for me
 
> ## Navigation
> * [ ]   **Desktop** : There is no indication/sign that a 2nd level link leads to a 3rd one unless we hover it (desired behavior ?)

Septimus:  an oversight on my part, I'll do smthg for it 

> ## Config
> * [ ]  Should we forbid the possibility to add a multilingual setting to the header if the module "change-language" does not exist?

Septimus: yes, good point. Couldn't do it there myself, but it will be desired on the final product

> * [ ]  Should we restrict the language selector dropdown to the change-language module?

Septimus: well, the langage part of the header is meant to be an independant module, so the actual code template and limitations will come from the used langage system
![image](https://user-images.githubusercontent.com/28646786/189909581-01c8c1a8-5b45-4a2d-9c3f-add3d1ddac13.png)

> * [ ]  The search config should have the GET argument name, we might want to use another term than "keywords"

Septimus: good point, but to me seems like an overkill feature for now. the current search field is built in the header module, meant as a simple and standard feature with little to no config needed. If there is specific needs for a more intricate search module, we could easily overwrite the module template to accomodate the search field.
On the other hand, we could change the page selector field to a module selector field - like for the langage part - and completely delegate this part. @LupusVII your thoughts ?

**Comment by LupusVII** [comment]
> > ## Logo
> > 
> > * [ ]   On the homepage, should we keep the link on the logo?
> >   In the v1, we put the h1 on the logo, so we are sure to have a lvl 1 title coherent. But on some websites, the homepage can have a more pertinent h1 in the page, so maybe we should have a setting for that? Like a dropdown labeled "Logo wrapper on the homepage" with the options "div", "a" or "h1" ?
> 
> Septimus: could be... may be a bit of an overkill for now. @LupusVII your thoughts ?

Might be good enough for now, most of the Smartgear website do not have SEO issues. But we have to make sure there is no several h1 on the main page, and at least one who has meaning.

> > * [ ]   The translation, when going to a subpage, feels off. It comes from the bottom of the screen when the chevron points to the right.
> 
> Septimus: aware of this, but will take me a good chunk of time to improve that. Currently, I did mostly nothing on this animation, it is a product of the panels switch mechanic, and dealing with the animation may force me to change the way things works. For now it's good enough for me, @LupusVII your thoughts on it ?

No, not necessary to spend too much time on an animation. We will wait for some feedback before doing anything.

> > * [ ]   The search config should have the GET argument name, we might want to use another term than "keywords"
> 
> Septimus: good point, but to me seems like an overkill feature for now. the current search field is built in the header module, meant as a simple and standard feature with little to no config needed. If there is specific needs for a more intricate search module, we could easily overwrite the module template to accomodate the search field. On the other hand, we could change the page selector field to a module selector field - like for the langage part - and completely delegate this part. @LupusVII your thoughts ?

Ok for me, we can have a default search "keywords" argument.

**Comment by SeptimusVII** [comment]
> > > * [ ]    The search config should have the GET argument name, we might want to use another term than "keywords"
> > 
> > 
> > Septimus: good point, but to me seems like an overkill feature for now. the current search field is built in the header module, meant as a simple and standard feature with little to no config needed. If there is specific needs for a more intricate search module, we could easily overwrite the module template to accomodate the search field. On the other hand, we could change the page selector field to a module selector field - like for the langage part - and completely delegate this part. @LupusVII your thoughts ?
> 
> Ok for me, we can have a default search "keywords" argument.

I changed my mind on this

**Comment by SeptimusVII** [comment]
> ## Search
> * [x]  Once a search is done, the keywords appear in the URL but not in the search field (desired behavior ?)
> * [x]  Once a search is done, the search field should be deployed automatically

this search field, despite working in its current state, is highly messy in its conception and do not satisfy me. 

It is due to its collapsible nature, which do not works great with the resizing / switch-nav feature.
adding to this, it leads to ugly and unwanted behaviors when the header is bloated with content and features(long menu, extra content like catchline, body sized, etc...)

my recommandation to solve this would be to forget the collapsible feature of the search field, and instead have it in fixed layout, that would not mess with the resizing calculations.
An ideal place for it would be in the topbar.

**Comment by SeptimusVII** [comment]
@LupusVII  @ChipsVII 
i'm done for this review. If you have any more review and comments to do, feel free.
In the meantime i'll prepare the tasks for @ChipsVII in the main issue
