### ISSUE TITLE
Filters throwing incorrect results

### ISSUE THREAD

**Issue by SeptimusVII** [Web-Ex-Machina/contao-smartgear#210]
![image](https://user-images.githubusercontent.com/28646786/195111829-81795796-924c-4705-8613-dc6b3c8e5af2.png)

filters form doesn't work at the moment (see screenshot)
my guess: some fields in the form (date fields for instance) are built with names like "date[month]", which results in incorrect urls
![image](https://user-images.githubusercontent.com/28646786/195112665-c4f618a8-e8ad-408a-8676-09bbe653c64d.png)

Filters are used in Blog and Events lists

**Comment by ChipsVII** [comment]
A fix have been deployed on https://smartgear2.sandbox.webexmachina.fr/blog.html & https://smartgear2.sandbox.webexmachina.fr/agenda.html.
Can you check if it is ok for you ?
