### ISSUE TITLE
Grid Builder - preview doesn't refresh after editing content

### ISSUE THREAD

**Issue by SeptimusVII** [Web-Ex-Machina/contao-smartgear#223]
the preview should refresh after a user has edited a content element and closed the modal.
also there should be at least a "save & close" button in addition to the "save" one, in the edit modal
![image](https://user-images.githubusercontent.com/28646786/197570931-6a5770e8-4bbd-4479-8a5b-ad2fa6f911e7.png)

**Comment by ChipsVII** [comment]
Fixed in the contao-grid 1.0.0-rc10 version : https://github.com/Web-Ex-Machina/contao-grid/releases/tag/1.0.0-rc10
Both sandboxes have been updated
