### ISSUE TITLE
Socials config icon field is limited to 15 characters

### ISSUE THREAD

**Issue by SeptimusVII** [Web-Ex-Machina/contao-smartgear#311]
This is an issue when adding icons with more than 15 characters

![image](https://github.com/Web-Ex-Machina/contao-smartgear/assets/28646786/3a514130-3649-4d50-988e-e830799d5808)

**Comment by ChipsVII** [comment]
Fixed in https://github.com/Web-Ex-Machina/contao-smartgear/releases/tag/v1.0.40
